version: '2'
services:
  teambition-nginx-gateway:
    image: docker-registry.teambition.net/library/teambition-nginx-gateway:0.2.0
    container_name: teambition-gninx-gateway
    environment:
      APP_HOST: 'http://localhost'
      APP_CLIENT_ID: '78737a90-49bd-11e7-9659-95e4a6783161'
      APP_CLIENT_SECRET: 'ee4076c9-65d3-4e1e-a23f-c20fb3c58479'